@TodoApi_HostAddress = https://localhost:7135

GET {{TodoApi_HostAddress}}/api/todoitems

###

POST {{TodoApi_HostAddress}}/api/todoitems
Content-Type: application/json

{  
  "name": "Your Mom!",
  "isComplete": true  
}

###

GET {{TodoApi_HostAddress}}/api/todoitems/1

###

DELETE {{TodoApi_HostAddress}}/api/todoitems/1

###

PUT {{TodoApi_HostAddress}}/api/todoitems/2
Content-Type: application/json

{
  "id": 2,
  "name": "Your Dad!",
  "isComplete": true
}

###
